import type { CardData } from '../types';

const GITHUB_API_URL = 'https://api.github.com/gists';

function formatContentAsMarkdown(data: CardData): string {
  const { name, imageUrl, summary } = data;

  let content = `# Business Card for ${name}\n\n`;

  if (imageUrl) {
    content += `![Profile Picture for ${name}](${imageUrl})\n\n`;
  }

  content += `> ${summary}\n\n`;
  content += `---\n`;
  content += `Generated by the AI Business Card Generator.`;

  return content;
}

export async function createGist(cardData: CardData): Promise<string> {
  const content = formatContentAsMarkdown(cardData);

  const payload = {
    description: `AI-Generated Business Card for ${cardData.name}`,
    public: true,
    files: {
      'business-card.md': {
        content: content,
      },
    },
  };

  try {
    const response = await fetch(GITHUB_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/vnd.github.v3+json',
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.message || `GitHub API responded with status ${response.status}`);
    }

    const gistData = await response.json();
    return gistData.html_url;
  } catch (error) {
    console.error('Error creating GitHub Gist:', error);
    throw new Error('Could not connect to the GitHub API.');
  }
}
